import java.util.*;

class AddOnService {
    private final String name;
    private final double price;

    public AddOnService(String name, double price) {
        this.name = name;
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }

    @Override
    public String toString() {
        return name + " ($" + price + ")";
    }
}

class AddOnServiceManager {
    private final Map<String, List<AddOnService>> reservationServices = new HashMap<>();

    public void addServiceToReservation(String reservationID, AddOnService service) {
        reservationServices.putIfAbsent(reservationID, new ArrayList<>());
        reservationServices.get(reservationID).add(service);
    }

    public List<AddOnService> getServicesForReservation(String reservationID) {
        return reservationServices.getOrDefault(reservationID, Collections.emptyList());
    }

    public double calculateTotalAddOnCost(String reservationID) {
        return getServicesForReservation(reservationID).stream()
                .mapToDouble(AddOnService::getPrice)
                .sum();
    }

    public void displayServices(String reservationID) {
        List<AddOnService> services = getServicesForReservation(reservationID);
        if (services.isEmpty()) {
            System.out.println("No add-on services for reservation " + reservationID);
        } else {
            System.out.println("Add-on services for reservation " + reservationID + ": " + services);
            System.out.println("Total add-on cost: $" + calculateTotalAddOnCost(reservationID));
        }
    }
}

// Example BookingService and RoomInventory from previous use case
class Reservation {
    private final String guestName;
    private final String roomType;

    public Reservation(String guestName, String roomType) {
        this.guestName = guestName;
        this.roomType = roomType;
    }

    public String getGuestName() { return guestName; }
    public String getRoomType() { return roomType; }
}

public class AddOnServiceSelection {
    public static void main(String[] args) {
        // Assume we already have a reservation assigned
        String reservationID = "Single-1"; // could be generated by BookingService

        AddOnService breakfast = new AddOnService("Breakfast", 15);
        AddOnService spa = new AddOnService("Spa Access", 50);
        AddOnService airportPickup = new AddOnService("Airport Pickup", 30);

        AddOnServiceManager serviceManager = new AddOnServiceManager();

        // Guest selects multiple services
        serviceManager.addServiceToReservation(reservationID, breakfast);
        serviceManager.addServiceToReservation(reservationID, spa);
        serviceManager.addServiceToReservation(reservationID, airportPickup);

        // Display selected services and total cost
        serviceManager.displayServices(reservationID);
    }
}